language: c
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.8.9-linux64.tar.xz
  - tar xf arduino-1.8.9-linux64.tar.xz
  - sudo mv arduino-1.8.9 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino

    # Arduino IDE adds a lot of noise caused by network traffic, trying to firewall it off
  - sudo iptables -P INPUT DROP
  - sudo iptables -P FORWARD DROP
  - sudo iptables -P OUTPUT ACCEPT
  - sudo iptables -A INPUT -i lo -j ACCEPT
  - sudo iptables -A OUTPUT -o lo -j ACCEPT
  - sudo iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
install:
  - ln -s $PWD /usr/local/share/arduino/libraries/SparkFun_MCP9600_Arduino_Library
  - arduino --install-boards arduino:samd
  - arduino --pref "boardsmanager.additional.urls=https://raw.githubusercontent.com/sparkfun/Arduino_Boards/master/IDE_Board_Manager/package_sparkfun_index.json" --save-prefs
  - arduino --install-boards SparkFun:samd
  - arduino --install-boards SparkFun:apollo3
  - arduino --install-boards SparkFun:avr
  - arduino --pref "boardsmanager.additional.urls=https://adafruit.github.io/arduino-board-index/package_adafruit_index.json" --save-prefs
  - arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json" --save-prefs

script:
  #compile for arduino AVR
  - echo Compiling for Arduino AVR...
  - arduino --verify --board arduino:avr:uno $PWD/examples/Example1_PrintButtonStatus/Example1_PrintButtonStatus.ino

  #compile for arduino SAMD
  - echo Compiling for Arduino SAMD...
  - arduino --verify --board arduino:samd:arduino_zero_edbg $PWD/examples/Example1_PrintButtonStatus/Example1_PrintButtonStatus.ino

  #compile for SparkFun AVR
  - echo Compiling for SparkFun AVR...
  - arduino --verify --board SparkFun:avr:RedBoard $PWD/examples/Example1_PrintButtonStatus/Example1_PrintButtonStatus.ino

  #compile for SparkFun SAMD
  - echo Compiling for SparkFun SAMD...
  - arduino --verify --board SparkFun:samd:samd51_thing_plus $PWD/examples/Example1_PrintButtonStatus/Example1_PrintButtonStatus.ino

  #compile for SparkFun Artemis
  - echo Compiling for SparkFun Artemis...
  - arduino --verify --board SparkFun:apollo3:amap3blackboard $PWD/examples/Example1_PrintButtonStatus/Example1_PrintButtonStatus.ino

notifications:
  email:
    on_failure: change